export const types = {
  GET_TIMER_DETAILS: 'GET_TIMER_DETAILS'
}

export const LOGIN_ACTIONS = {
  LOGIN_GOOGLE_ATTEMPT: 'LOGIN_GOOGLE_ATTEMPT',
  LOGIN_FACEBOOK_ATTEMPT: 'LOGIN_FACEBOOK_ATTEMPT',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGIN_CANCEL: 'LOGIN_CANCEL',
  LOGOUT_ATTEMPT: 'LOGOUT_ATTEMPT',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_ERROR: 'LOGOUT_ERROR',
  LOGIN_ANONYMOUS: 'LOGIN_ANONYMOUS',
  ADD_NEW_TIMER_TO_LIST: 'ADD_NEW_TIMER_TO_LIST'  
}

export const APP_ACTIONS = {
  EDIT_MODE_ON: 'EDIT_MODE_ON',
  EDIT_MODE_OFF: 'EDIT_MODE_OFF',
  START_TIMER_COUNTDOWN: 'START_TIMER_COUNTDOWN',
  STOP_TIMER_COUNTDOWN: 'STOP_TIMER_COUNTDOWN',
  TIMER_COMPLETE: 'TIMER_COMPLETE',
  SET_SELECTED_TIMER_DETAILS: 'SET_SELECTED_TIMER_DETAILS'
}
