export const types = {
  GET_TIMER_DETAILS: 'GET_TIMER_DETAILS'
}

export const LOGIN_ACTIONS = {
  LOGIN_GOOGLE: 'LOGIN_GOOGLE',
  LOGIN_FACEBOOK: 'LOGIN_FACEBOOK',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGIN_CANCEL: 'LOGIN_CANCEL',
  LOGOUT: 'LOGOUT',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_ERROR: 'LOGOUT_ERROR',
  LOGIN_ANONYMOUS: 'LOGIN_ANONYMOUS'
}